### ISSUE TITLE
[Proposal] accept capitalised `Project Names`

### ISSUE THREAD

**Issue by 404ram** [AleoHQ/aleo#176]
## 💥 Proposal

Seeing this error:

- ![image](https://user-images.githubusercontent.com/33354436/140781015-bf5d1608-2a06-4297-8436-20e4a10c2372.png)

is a bit confusing, the suggestion is to either accept capitalised `Project Names` or indicate that capitals are **not** allowed, I know in a regex world [a-z] means just lower cases etc, but the text is a bit unclear ..

**Comment by collinc97** [comment]
This error is not for the Aleo SDK
