### ISSUE TITLE
[Bug] Unable to Deploy Program with Imports to Local Aleo Node

### ISSUE THREAD

**Issue by fulltimemike** [AleoHQ/aleo#303]
## 🐛 Bug Report

Aleo programs with multiple files (one `main.aleo` file, one imported `helper.aleo` file) cannot deploy because the [initialization in SnarkVM](https://github.com/AleoHQ/snarkVM/blob/7837e41bd2b291b8c8d6a07c22d1811fea302b9e/vm/compiler/src/process/stack/helpers/initialize.rs#L35-L44) expects the imported program to be deployed already.

## Steps to Reproduce

Run `aleo node start` in a program with at least one imported aleo file.

#### Code snippet to reproduce

main.aleo file
```
import importtest.aleo;

// The 'main.aleo' program.
program token.main;

function hello:
    // Dummy input
    input r0 as address.public;
    // Dummy input
    input r1 as u64.public;
```

importtest.aleo file
```
program importtest.aleo;

function hello:
    // Dummy input
    input r0 as address.public;
    // Dummy input
    input r1 as u64.public;
```

#### Stack trace & error message

```
📦 Deploying 'token.aleo' to the local development node...

⚠️  Cannot add program 'main.aleo' because its import 'importtest.aleo' must be added first
```

## Expected Behavior

Programs with local imported files should deploy successfully. Local imports should be deployed to the local Aleo Node before the main program.

## Your Environment

- Aleo Version: built from source code
- Rust Version: rustc 1.65.0-nightly
- Computer OS: macOS Monetery Version 12.5

**Comment by howardwu** [comment]
Thank you for catching this! Assigning it to myself to fix.

**Comment by howardwu** [comment]
@fulltimemike This issue should be resolved now. I've added an example program that imports 4 Aleo programs, in the `examples/` folder. From my local build, `aleo node start` (following #307) is able to deploy all 4 imports and then the main program.

**Comment by fulltimemike** [comment]
Thanks a bunch @howardwu!
