### ISSUE TITLE
[Bug] Transfer Function doesn't Work

### ISSUE THREAD

**Issue by FranFiuba** [AleoHQ/aleo#315]
## 🐛 Bug Report

Created a transfer endpoint on a forked repo -> https://github.com/Entropy1729/aleo/pull/4/files

It seems that are some bugs related to the create_transfer function on the ledger.rs of the client.

1. The function tries to consume the record with the lowest amount of gates. This generates that when the amount to be transferred is greater than the number of gates of the record, the transfer cannot be carried out. 

This error was resolved by changing min_by to max_by, on the records lookup. 

2. When a transfer is made, it seems that it consumes a record that is also trying to consume the transfer used to generate transactions, which blocks the generation of blocks.

## Steps to Reproduce

Run 

`curl -X POST http://0.0.0.0:4180/testnet3/transfer -H 'Content-Type: application/json' -d '{"to": "NewAddress", "amount":700000000}'`

#### Stack trace & error message

`Serial number '4089065859010301472916859160003200087111650892897426850644464939793352274911field' already exists in the ledger

🛡️  Produced block 4 (ab16ljf59r3d8t25y6wzqs40z3tm34s8dm3xxt8cjazq53p59v2xcqqpk4qun)

{
  "previous_state_root": "3364010905788773857973743228842458740809350980788858797789209934619623548296field",
  "transactions_root": "8249325785024399288466739230704435237326997204634167570625238085849968763798field",
  "metadata": {
    "network": 3,
    "round": 4,
    "height": 4,
    "coinbase_target": 18446744073709551615,
    "proof_target": 18446744073709551615,
    "timestamp": 1660855184
  }
}`

## Expected Behavior

It should carry out the transfer and continue the generation of blocks.

## Your Environment

- Aleo Version
https://github.com/AleoHQ/aleo/commit/acd1685ce7e5137a091b785e491f1722bdf7e51e

**Comment by iamalwaysuncomfortable** [comment]
The aleo cli can now do this directly, by using `aleo transfer -h` you can see the exact methods for using the transfer function for your desired use-case
