### ISSUE TITLE
[Proposal] Remove local node development code and run snarkOS internally

### ISSUE THREAD

**Issue by jrchatruc** [AleoHQ/aleo#347]
## 💥 Proposal
Currently, `aleo node start` runs a local development node whose code is entirely contained in this repo. This is a problem because it duplicates the code contained in snarkOS. If changes need to be made to the REST API, both this repo and snarkOS need to be changed, which is unnecessary and makes the two nodes become de-synced, as people forget to update one or the other. 

Instead, the local node spun up by `aleo node start` should use the snarkOS development mode internally.

This issue depends on [this other issue](https://github.com/AleoHQ/snarkOS/issues/1914), which proposes adding a flag to start snarkOS in for local development mode.

**Comment by iamalwaysuncomfortable** [comment]
This command has been removed, we are re-designing the clis a bit so we should have a unified one with this command soon, thanks for the update!
