### ISSUE TITLE
[Proposal] Deploy command refactor

### ISSUE THREAD

**Issue by jrchatruc** [AleoHQ/aleo#364]
## 💥 Proposal

The `aleo deploy` command currently delegates most of its behaviour to `snarkVM`, including broadcasting the transaction to the blockchain. This is not ideal, as the VM should only be concerned with the crafting of the transaction (i.e. the execution/proof generation), but not the broadcasting aspect; instead, it should return the `Deployment`, which the CLI then converts into a transaction and broadcasts.

This also allow us to remove the custom `deploy` node endpoint, which currently just (almost) duplicates the `broadcast` logic.

**Comment by iamalwaysuncomfortable** [comment]
Thanks for this suggestion! An `aleo deploy` command has since been added which references the Aleo `rust sdk`. Thank you for the forethought in this matter.
