### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gsulaberidze** [AleoHQ/aleo#432]
## Your Environment

- 
- 
-

**Comment by arosboro** [comment]
I was working with @gsulaberidze on installing aleo

Here is a screen shot from our recording where he managed to get stuck.

![Screen Shot 2022-12-09 at 1 11 19 PM](https://user-images.githubusercontent.com/2224595/206766032-52c2c501-aae8-455e-a832-eeca5d502d7b.png)

**Comment by arosboro** [comment]
Sula a dependency failed to download, maybe try running the install command on the system affected again after some time.  If it sucessfully installs, you can close this issue.

**Comment by Nixonu** [comment]
I have same issue

**Comment by Nixonu** [comment]
', /home/nixonu/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.80/build/find_normal.rs:191:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `aleo v0.3.2 (/home/name/aleo)`, intermediate artifacts can be found at `/home/nixonu/aleo/target`

**Comment by iamalwaysuncomfortable** [comment]
Closing issue due to the age of the issue, let us know if this issue still persists.
