### ISSUE TITLE
[Bug] I16 is_neq return type is not valid

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/aleo#520]
# I16 is_neq return type is not valid

We (@fuzzinglabs) found an error in `is_neq` while fuzzing.

```sh
cat main.aleo && aleo build
program function_with_xor_add.aleo;

function hello:
        is.neq 42i16 12i16 into r0;
        div.w r0 1i16 into r1;
        output r1 as i16.private;

⏳ Compiling 'function_with_xor_add.aleo'...

⚠️  Invalid operand types for the 'div.w' instruction
```

## Your Environment
-  Aleo commit: b371a041b07fe23543ade4fe460d8a0d30775cfc
-  rustc 1.66.0-nightly (a37499ae6 2022-09-18)
-  Ubuntu 20.04

## Why is this an error ?

Based on the documentation the following happens:
```
function hello:
        is.neq 42i16 12i16 into r0; // r0 = i16
        div.w r0 1i16 into r1; // div.w i16 i16 -> r1 = i16
        output r1 as i16.private;
```

Based on the documentation, at: https://developer.aleo.org/aleo/opcodes#divw, the div.w instruction, when called with 2 `i16`, should work.

When testing by replacing `r0` by a random `i16` in the instruction, the code compiles.

The problem seems then to be in `is.neq`. Still based on the documentation, at: https://developer.aleo.org/aleo/opcodes#isneq, the `is.neq` function, when called with 2 `i16`, should store the result in the destination as an `i16`:

| First	| Second | Destination |
| ----------- | ----------- | ----------- |
| I16	      | I16	        | I16         |

So according to the documentation, our code should compile.

There may be either an error in the documentation or in the Aleo parser/compiler, as the code is valid as per the documentation

**Comment by d0cd** [comment]
This appears to be an issue in the documentation.
The output of an `is` operation is a `Boolean`, according to snarkVM.
https://github.com/AleoHQ/snarkVM/blob/testnet3/synthesizer/src/program/instruction/operation/is.rs
