### ISSUE TITLE
 WARN Unable to connect to '167.71.219.176:4133' - '167.71.219.176:4133' did not follow the handshake protocol: received "ChallengeRequest" instead of Message::ChallengeResponse

### ISSUE THREAD

**Issue by josephtouha** [AleoHQ/aleo#535]
## 🐛 Bug Report

(Write your description here)

#### Code snippet to reproduce

```
# Add code here
```

#### Stack trace & error message

```
// Paste the output here
```

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
-

**Comment by iamalwaysuncomfortable** [comment]
Closing due to underspecification of issue. Please let us know if this issue persists with a more complete bug report and we'll be sure to attend to it!
