### ISSUE TITLE
[Bug] counterintuitive syntax when handling negative numbers

### ISSUE THREAD

**Issue by pventuzelo** [AleoHQ/aleo#541]
We (@fuzzinglabs) found something that may be counterintuitive in the Leo syntax/grammar.
​
Our fuzzer generated some test cases looking like this:
​
```Rust
program foo.aleo {
	transition fuzz() -> i64 {
		let r0: i64 = -1i64.abs();
		return r0;
	}
}
```
​
By looking at this, we thought it would return `1`, as it is the absolute of `-1`.
​
Contrary to our expectations, it returned `-1`.
​
We first thought it was an error in the parsing or in the `abs()` function, but this pattern repeated on multiple operations.
​
We found that compared to the Aleo code we thought would be produced:
​
```
program foo.aleo;
​
​
function fuzz:
    abs -1i64 into r0;
    output r0 as i64.private;
```
​
It produced this one
​
```
program foo.aleo;
​
​
function fuzz:
    abs 1i64 into r0;
    neg r0 into r1;
    output r1 as i64.private;
```
​
So the compiler sees this code like this:
​
```Rust
program foo.aleo {
	transition fuzz() -> i64 {
		let r0: i64 = -(1i64.abs());
		return r0;
	}
}
```
​
When we initially interpreted that more like this:
​
```Rust
program foo.aleo {
	transition fuzz() -> i64 {
		let r0: i64 = (-1i64).abs();
		return r0;
	}
}
```
​
Based on some private discussions with the developer team, we found that it was the intended behavior, as specified in the abnf grammar, and is the default behavior of a lot of parsers.
​
So on the line `let r0: i64 = -1i64.abs();`, the parser understand something like that `let r0: i64 = -(1i64.abs());`.
​
Users may have to be careful when using negative numbers to call a function to avoid unwanted behavior

We open this issue to keep track of this behavior and to provide additional examples for unit testing.

**Comment by pventuzelo** [comment]
related PR for leo: https://github.com/AleoHQ/leo/pull/2344

**Comment by iamalwaysuncomfortable** [comment]
Looks like that issue was merged into leo and thus taken care of, so closing this issue. Thanks for your diligence on this. If you feel it needs further addressing, I'll re-open it.
