### ISSUE TITLE
[Bug] Signature verifies despite message not matching

### ISSUE THREAD

**Issue by niklaslong** [AleoHQ/aleo#600]
We haven't yet figured out the pattern but it seems like the signature for a message will sometimes incorrectly pass verification. Credit: @SplittyDev. 

 A few examples below:

![CleanShot 2023-06-12 at 19 02 31@2x](https://github.com/AleoHQ/sdk/assets/13221615/6d6e18c7-6068-470d-8ac4-ba3a45525251)
![CleanShot 2023-06-12 at 19 02 58@2x](https://github.com/AleoHQ/sdk/assets/13221615/0337da1a-8155-4e73-84d4-adac256633c4)

And here verification works as expected:

![CleanShot 2023-06-12 at 19 05 02@2x](https://github.com/AleoHQ/sdk/assets/13221615/5e74081a-cb9a-43ee-a38d-83223d0b8d70)

Edit: a few more experiments by @vvp seem to suggest any message under 32 chars will pass verification when padded with `[jklmnozJKLMNOZ]`. 

Edit2: there are a few more chars: `¤`, `€`, `/`, `=`, the scandinavian/nordic letters... perhaps some fuzzing is in order?

**Comment by iamalwaysuncomfortable** [comment]
We're investigating this now

**Comment by iamalwaysuncomfortable** [comment]
This was a text encoding issue within javascript. PR #607 addresses this. Thanks for identifying the issue.
