### ISSUE TITLE
[Bug] Split doesn't work

### ISSUE THREAD

**Issue by liolikus** [AleoHQ/aleo#601]
## 🐛 Bug Report
Split `RECORD` doesn't work 
## Steps to Reproduce

![image](https://github.com/AleoHQ/sdk/assets/85246338/31bbe5ba-6050-41c3-8632-24a8466e5c97)

**Comment by iamalwaysuncomfortable** [comment]
Thanks for the bug report!

We've pushed a fix via #606 - thank you for the attention!

**Comment by iamalwaysuncomfortable** [comment]
The fix has gone live to [aleo.tools](https://aleo.tools) - we really appreciate your attention to this

**Comment by liolikus** [comment]
Now, this error
![image](https://github.com/AleoHQ/sdk/assets/85246338/a9e47a14-3635-4ad9-977d-5e0a17255782)

**Comment by iamalwaysuncomfortable** [comment]
Thanks again, fixed :)
