### ISSUE TITLE
[Proposal] Implement Syntax Highlighting in aleo.tools

### ISSUE THREAD

**Issue by onetrickwolf** [AleoHQ/aleo#610]
## 💥 Proposal - Implement Syntax Highlighting in aleo.tools

When a user views a program on aleo.tools, the text box should be able to recognize Aleo instruction syntax and apply appropriate coloring and styling to the code elements.

**Comment by liolikus** [comment]
![image](https://github.com/AleoHQ/sdk/assets/85246338/5c4ec581-19a8-4dc8-95ca-1827464c657d)
doesn't work for deployment box

**Comment by onetrickwolf** [comment]
@liolikus fixed thanks for letting us know!
