### ISSUE TITLE
[Proposal] coin types for BIP-0044

### ISSUE THREAD

**Issue by daoauth** [AleoHQ/aleo#611]
## 💥 Proposal

I propose using the coin type 0x8000a1e0 (41440) as the coin type for aleo.

```
const path = 'm/44'/41440'/0'/0'/0'';
```

https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by iamalwaysuncomfortable** [comment]
I appreciate the thought towards this, can you expand your thoughts on this further?

**Comment by daoauth** [comment]
I'm a multichain wallet developer.

Many chains have registered their unique coin types with BIP44 and use an account system that follows the BIP44 scheme.

aptos: [m/44'/637'/0'/0'/0'](https://github.com/aptos-labs/aptos-core/blob/25844c936b27a3f8dbe8d8b93f99973d90f55a4c/ecosystem/typescript/sdk/src/account/aptos_account.ts#L52
)
sui: [m/44'/784'/0'/0'/0'](https://github.com/MystenLabs/sui/blob/e9cd21a3d096e1c0a3747a46b19939a0c5246923/sdk/typescript/src/cryptography/ed25519-keypair.ts#L123)
near: [m/44'/397'/0'/0'/0'](https://github.com/near/near-wallet/blob/002f98115b948746de7945b88c18d8c36b6780ad/packages/frontend/src/redux/slices/ledger/index.js#L18)

BIP44, including BIP32 and 39, will be able to utilize a single mnemonic to provide the flexibility to create multiple accounts on multiple chains for different purposes.

@iamalwaysuncomfortable

**Comment by onetrickwolf** [comment]
Looks like someone added Aleo as 683: https://github.com/satoshilabs/slips/pull/1599/files
