### ISSUE TITLE
[Bug] The UI elements of the top nav are not optimized for different browser size windows

### ISSUE THREAD

**Issue by ghost** [AleoHQ/aleo#619]
## 🐛 Bug Report

The top nav bar of [aleo.tools](https://aleo.tools/) dynamically adjusts to different browser window sizes. However, the UI elements do not change size and end up displaying in a funky way.

### Reference screenshot 1 (normal view):
<img width="1209" alt="Screenshot 2023-06-21 at 09 43 05" src="https://github.com/AleoHQ/sdk/assets/17191728/03cfbb6c-7d32-4507-b02d-c20913696057">

### Reference screenshot 2 (funky formatting):
* specifically noting  `Develop` and `Transfer`

![image](https://github.com/AleoHQ/sdk/assets/17191728/04cf84b7-378e-46dd-a04d-eb870bbbc8a6)

### Reference screenshot 3 (smaller size - funky formatting):
* however, this also happens to any number of UI elements in the nav bar depending on the size of the window

<img width="537" alt="Screenshot 2023-06-21 at 10 14 54" src="https://github.com/AleoHQ/sdk/assets/17191728/1332f149-bc1e-4abb-b882-93deac94d51e">

## Steps to Reproduce

- Navigate to [aleo.tools](https://aleo.tools/)
- Enter [full screen mode](https://support.apple.com/guide/mac-help/use-apps-in-full-screen-mchl9c21d2be/mac)
- Enter [Split View](https://support.apple.com/en-us/HT204948) by adding a second window
- Adjust the size of the original window that contains aleo.tools to be smaller until you see the "funky formatting"

## Expected Behavior

- Ideally, the UI elements would adjust according to the size of the browser window so that all of the nav bar elements are visible/not moved to the second line.
- Another, potentially better option, would be to change the nav bar to a hamburger menu ([ref](https://www.justinmind.com/blog/hamburger-menu/)) such that the nav bar items are moved to a hidden drawer when at a specific browser window size; doing so would also optimize better for mobile.

## Your Environment
- MacOS 13.4 (22F66)
- Google Chrome Version 114.0.5735.133 (Official Build) (arm64)

**Comment by iamalwaysuncomfortable** [comment]
Thank you for pointing this out - we have a team member working on the Aleo web experience so this should be re-designed within the coming 30 days
