### ISSUE TITLE
[Docs] Add documentation on how to use the sdk for web development

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [AleoHQ/aleo#626]
## 📚 Documentation

The Aleo SDK documents are out of date. The following docs need a revision

- [x] The main Readme.md in the SDK repo needs a comprehensive revision to explain how to employ Aleo SDKs in the web. It should include specific instruction on how to use `aleo-wasm` to build a web app
- [x] #691
- [x] The @aleohq/sdk should have its documents amended as well.

**Comment by collinc97** [comment]
Live updates pushed to https://developer.aleo.org/sdk/

**Comment by collinc97** [comment]
For the first bullet point: add the WASM package [README](https://github.com/AleoHQ/sdk/tree/testnet3/wasm) to the Welcome [docs](https://developer.aleo.org/sdk/) under a new WASM section on the left sidebar. @moAlobaidi

**Comment by moAlobaidi** [comment]
@collinc97 Just pushed up a PR to add the current wasm README to the docs [here](https://github.com/AleoHQ/welcome/pull/248).

**Comment by iamalwaysuncomfortable** [comment]
Finished by:

#718 
#722
