### ISSUE TITLE
[Bug] Aleo SDK `AleoNetworkClient` method `findUnspentRecords` dose not index records used for fee

### ISSUE THREAD

**Issue by BeroBurny** [AleoHQ/aleo#633]
## 🐛 Bug Report

Inside Aleo SDK `AleoNetworkClient` method `findUnspentRecords` dose not index records used for fee

## Steps to Reproduce

1. get at least 2 records
2. initiate transaction with this 2 records
3. run `findUnspentRecords` and you will receive x -1 of records

#### Code snippet to reproduce

N/A

#### Stack trace & error message

N/A

## Expected Behavior

To return records that contains resulting records from `fee` field

## Your Environment

- 
- 
-

**Comment by iamalwaysuncomfortable** [comment]
Thanks for the bug report, we'll look into this issue and if we find anything, will fix the errors

**Comment by iamalwaysuncomfortable** [comment]
We haven't actually been able to reproduce this. Can you please submit a code sample which recreates the issues you're experiencing?

**Comment by iamalwaysuncomfortable** [comment]
This has been solved, thank you for bringing this to our attention
