### ISSUE TITLE
[Bug] Can't execute a deployed program that contains imports

### ISSUE THREAD

**Issue by Armin-FalDiS** [AleoHQ/aleo#660]
## 🐛 Bug Report

I have created a project for the Aleo incentives but I have trouble with its execution.
My program is deployed on the testnet and can be seen [here](https://vm.aleo.org/api/testnet3/program/shadow_swap_test1.aleo).
But upon attempting to execute it, I get the following error:

![image](https://github.com/AleoHQ/sdk/assets/20294274/397272d2-b225-405a-a090-7c7769d83013)

Do note that I have no trouble executing the programs that this on depends on (imports).

## Steps to Reproduce

Simply try to execute any function of the program `shadow_swap_test1.aleo`.

#### Code snippet to reproduce

```
aleo execute shadow_swap_test1.aleo mint_lp_init_shadow "ADDRESS" "RECORD" "1u64" "RECORD" "2u64" -k "PRIVATE_KEY" --fee 1 -r "FEE_RECORD"
```

#### Stack trace & error message

```
Attempting to execute function 'shadow_swap_test1.aleo:mint_lp_init_shadow' with a fee of 1 credits
Using default peer: https://vm.aleo.org/api/testnet3
Attempting to find program: shadow_swap_test1.aleo
Executing 'shadow_swap_test1.aleo:mint_lp_init_shadow'
Building transaction..
Checking function mint_lp_init_shadow exists in shadow_swap_test1.aleo
Execution of function 'shadow_swap_test1.aleo:mint_lp_init_shadow' failed with error:
⚠️  Program 'shadow_swap_test1.aleo' does not exist
```

## Expected Behavior

It was supposed to run the program but instead it says the program does not exist.

## Your Environment

- Aleo SDK Version 0.5.0
- Rust Version 1.71.0
- Ubuntu 22.04 (WSL2)

This bug is also present on other environments, aleo.tools website and snarkOS.

**Comment by iamalwaysuncomfortable** [comment]
Thanks for identifying this!  This is because the program has an input and the cli does not yet handle imports properly. We'll be updating the SDK today for the latest SnarkVM release and that should solve this issue. Thank you very much for bringing this attention!

**Comment by iamalwaysuncomfortable** [comment]
@Armin-FalDiS This bug has been fixed. Programs with imports should now execute and deploy properly using the aleo cli, rust sdk, and wasm sdk and on aleo.tools

**Comment by Armin-FalDiS** [comment]
> @Armin-FalDiS This bug has been fixed. Programs with imports should now execute and deploy properly using the aleo cli, rust sdk, and wasm sdk and on aleo.tools

Thank you very much for a speedy fix!
