### ISSUE TITLE
[Bug] Aleo.tools fails to load on mobile or slow connections sometimes

### ISSUE THREAD

**Issue by onetrickwolf** [AleoHQ/aleo#681]
Aleo.tools won't render until the full wasm is downloaded. This file is pretty large (~8MB) so on slower connections or mobile it may appear the site is broken (just a white screen) until everything is done loading. Furthermore, if the wasm is downloaded slow enough, the site seems to have an error where it will not render at all; this forces the user to refresh which will cause the site to usually render properly as the wasm is now being pulled instantly from the cache.

Proposed fixes:
- Have some earlier first paint indicating the site is loading
- Fix condition where sites fails to render is wasm is not loaded fast enough (make sure we are properly waiting until it is loaded to try to initiate)
- Potentially looks into faster edge CDNs for the larger files

Replication:
- Clear cache on any browser and reload (sometimes occurs)
- Clear cache on any browser and reload with speed limiting (consistently occurs)
- Try hard reloading on iOS Safari (consistently occurs)

**Comment by iamalwaysuncomfortable** [comment]
This can likely be partially mitigated by reducing the size of the wasm binary
