### ISSUE TITLE
[Docs] Ensure JS Doc comments in the WASM SDK are in JS Doc format

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [AleoHQ/aleo#684]
## 📚 Documentation

Currently the wasm documentation is being automatically pulled from the `javascript` `wasm` bindings generated from `wasm-pack build` and put onto the Aleo Developer hub. However, not all fields in the wasm documentation are in JsDoc format. All objects, methods, and functions in the wasm SDK should be documented in JsDoc format.

**Comment by collinc97** [comment]
Closed by https://github.com/AleoHQ/sdk/pull/685
