### ISSUE TITLE
Create conditional feature selection in the Aleo SDK that determines Node vs. Web environment

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [AleoHQ/aleo#689]
Currently there are two versions of the wasm SDK. One that uses browser specific functionality like web workers and one that uses nodejs specific paradigms. The Aleo SDK should optimally be able to detect whether it's being used from NodeJS or from a browser environment so that the a single package should be used.

**Comment by onetrickwolf** [comment]
Closed https://github.com/AleoHQ/sdk/pull/705 want to wait until the TS SDK transition is done before looking at this again.
