### ISSUE TITLE
[Feature] snarkos developer scan should display the block number too

### ISSUE THREAD

**Issue by kaxxa123** [AleoHQ/aleo#737]
## 🚀 Feature

`snarkos developer scan` should display the block number together with the decrypted record.

## Motivation

When working with a development node, it is handy to have the block number as it provides a time reference and helps when running subsequent scans (reducing the need to scan the entire chain).

## Implementation

Update snarkos

**Comment by onetrickwolf** [comment]
@kaxxa123 did you mean to submit this to https://github.com/AleoHQ/snarkOS?

**Comment by kaxxa123** [comment]
you are right. sorry for that.
