### ISSUE TITLE
showig private key error please fix  i done testing [Bug]

### ISSUE THREAD

**Issue by 7066549259** [AleoHQ/aleo#751]
## 🐛 Bug Report

(Write your description here)

#### Code snippet to reproduce

```
# Add code here
```

#### Stack trace & error message

```
// Paste the output here
```

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
-

**Comment by onetrickwolf** [comment]
@7066549259 can you provide more information?

**Comment by iamalwaysuncomfortable** [comment]
Closing due to lack of actionable information, please file a new issue with the exact description of the issue you're experiencing
