### ISSUE TITLE
[Bug] Deploy a program to the aleo network error -- error fetching program

### ISSUE THREAD

**Issue by YaakovHuang** [AleoHQ/aleo#791]
## 🐛 Bug Report
An error occurred when deploying the program to the aleo network.
```
@aleohq/sdk/dist/index.js:548 throw new Error("Error fetching program")
```
Then I traced the code and found that  `index.js:1357`  was missing the keyword `await` .
## Steps to Reproduce
```
const txId = await programManager.deploy(program, fee);
```

## Your Environment

>sdk: 0.6.2

**Comment by onetrickwolf** [comment]
@YaakovHuang I believed we fixed this if you want to try the latest SDK: https://github.com/AleoHQ/sdk/commit/3a06c3c41bbf494f784196e6bbeb09e9e3f2b6e2
