### ISSUE TITLE
[Bug] Having error with latest create-leo-app

### ISSUE THREAD

**Issue by zklimaleo** [AleoHQ/aleo#941]
## 🐛 Bug Report

Follow guide to run `create-leo-app` but encounter error during run dev. Noticed the update of `@provablehq/sdk` to `0.7.0`. Fallback to `0.6.13` works.

#### Code snippet to reproduce

```
npm create leo-app@latest
cd aleo-project
npm install
npm run dev
```

#### Stack trace & error message

```bash
Failed to resolve import "core-js/proposals/json-parse-with-source.js" from "node_modules/@provablehq/sdk/dist/testnet/browser.js?v=cc7fe778". Does the file exist?
6:05:15 PM [vite] Internal server error: Failed to resolve import "core-js/proposals/json-parse-with-source.js" from "node_modules/@provablehq/sdk/dist/testnet/browser.js?v=cc7fe778". Does the file exist?
  Plugin: vite:import-analysis
  File: /aleo-project/node_modules/@provablehq/sdk/dist/testnet/browser.js?v=cc7fe778:1:9
  1  |  import 'core-js/proposals/json-parse-with-source.js';
     |          ^
  2  |  import { ViewKey, Address, PrivateKeyCiphertext, PrivateKey, RecordCiphertext, Program, Transaction, ProvingKey, VerifyingKey, ProgramManager as ProgramManager$1, RecordPlaintext, verifyFunctionExecution, Metadata } from '@provablehq/wasm/testnet.js';
  3  |  export { Address, ExecutionResponse, Field, Execution as FunctionExecution, OfflineQuery, PrivateKey, PrivateKeyCiphertext, Program, ProgramManager as ProgramManagerBase, ProvingKey, RecordCiphertext, RecordPlaintext, Signature, Transaction, VerifyingKey, ViewKey, initThreadPool, verifyFunctionExecution } from '@provablehq/wasm/testnet.js';
```

## Expected Behavior

Able to run dev without errors

## Your Environment

- create-leo-app Version - 0.7.3
- Provable SDK Version - 0.7.0
- Computer OS - MacOS Sequoia 15.0.1

**Comment by Neo-Gar** [comment]
Same issue

**Comment by RevelationOfTuring** [comment]
Same issue

**Comment by d0cd** [comment]
For context, this error only occurs when I run `npm create leo-app@latest` and select `Node.js` as the framework

**Comment by iamalwaysuncomfortable** [comment]
@Pauan any idea why this might be?

**Comment by zkxuerb** [comment]
This issue also occurs when running `npm create leo-app@latest` with `React`, and then building the project using `npm run build`.

**Comment by d0cd** [comment]
For the React option, I was able to get `npm run build` working after installing `core-js`.
For the Typescript option, I get this error when I get this error
```
> npm run dev
npm error Missing script: "dev"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /Users/pranav/.npm/_logs/2024-11-27T16_16_51_580Z-debug-0.log
```

**Comment by zklimaleo** [comment]
> For the React option, I was able to get `npm run build` working after installing `core-js`. For the Typescript option, I get this error when I get this error
> 
> ```
> > npm run dev
> npm error Missing script: "dev"
> npm error
> npm error To see a list of scripts, run:
> npm error   npm run
> npm error A complete log of this run can be found in: /Users/pranav/.npm/_logs/2024-11-27T16_16_51_580Z-debug-0.log
> ```

There's some errors printed in console and all functions from `worker.js` doesn't work even after installed `core-js` package for React option
<img width="586" alt="Screenshot 2024-11-28 at 12 54 19 AM" src="https://github.com/user-attachments/assets/bc24efae-45e7-4ece-bbf3-c4388391c31d">

**Comment by Pauan** [comment]
Thanks for the report, this seems to be caused by #925, I think we just need to update the examples.

**Comment by zklimaleo** [comment]
This update does not seems to have published to npm yet

**Comment by Pauan** [comment]
@zklimaleo Yes, that's correct, we plan to publish a new version soon.
